# Generated by Django 3.2.7 on 2021-09-03 08:17

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('letter_choices', models.CharField(help_text='Please Enter range as A-Z', max_length=3)),
                ('numbers_from', models.CharField(help_text='Please Enter range as 00-99', max_length=7)),
                ('total_tickets', models.PositiveIntegerField()),
                ('total_winners', models.PositiveIntegerField(default=1)),
                ('actual_closing_date', models.DateTimeField(null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('group_title', models.SmallIntegerField(choices=[(1, 'Featured Competition'), (2, 'Active Competition')])),
                ('move_section', models.SmallIntegerField(choices=[(1, 'Prepared Competitions'), (2, 'Ongoing Competitions'), (3, 'Archived Competitions')])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_text', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_active', models.BooleanField(default=False)),
                ('product_price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=25)),
                ('sold_time', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Available'), (2, 'Sold'), (3, 'Reserved')], default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='competitions.competition')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comititions')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competitions.competition')),
            ],
        ),
    ]
